### ISSUE TITLE
Using specific channels for AP

### ISSUE THREAD

**Issue by puccaso** [balenalabs/wifi-repeater#28]
Hello :wave, 

First off, love this project! 

I am attempting to select a specific channel for the AP point. 
Specifically, IOS is telling me that most likely, the AP is using a channel that others' around me are also using and it may be necessary to reboot the AP to auto-select a new channel. 

Kindly, 

puc.

**Comment by puccaso** [comment]
Ok just saw one of the pending PRs, with channel related code. 
gonna add
`const AP_CHANNEL = Number(process.env.AP_CHANNEL) || 6;`
and see what happens.

**Comment by puccaso** [comment]
ok nope. 
`[debug] handling message: {"message":"\u001b[32m[Success]\u001b[39m        Successfully uploaded images"}
[Success]        Successfully uploaded images
[debug] handling message: {"message":"\u001b[31m[Error]\u001b[39m          Some services failed to build:","isError":true}
[Error]          Some services failed to build:
[debug] handling message: {"message":"\u001b[31m[Error]\u001b[39m            Service: wifi-repeater","isError":true}
[Error]            Service: wifi-repeater
[debug] handling message: {"message":"\u001b[31m[Error]\u001b[39m              Error: The command '/bin/sh -c npm install && npm run build' returned a non-zero code: 2","isError":true}
[Error]              Error: The command '/bin/sh -c npm install && npm run build' returned a non-zero code: 2
[debug] handling message: {"message":"\u001b[36m[Info]\u001b[39m           Built on arm06"}
[Info]           Built on arm06
[debug] handling message: {"message":"\u001b[31m[Error]\u001b[39m          Not deploying release.","isError":true}
[Error]          Not deploying release.
Remote build failed

RemoteBuildFailedError: Remote build failed
    at handleRemoteBuildStream (/usr/local/lib/balena-cli/build/utils/remote-build.js:83:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.startRemoteBuild (/usr/local/lib/balena-cli/build/utils/remote-build.js:64:13)
    at async PushCmd.pushToCloud (/usr/local/lib/balena-cli/build/commands/push.js:78:27)
    at async PushCmd.run (/usr/local/lib/balena-cli/build/commands/push.js:32:17)
    at async PushCmd._run (/usr/local/lib/balena-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/usr/local/lib/balena-cli/node_modules/@oclif/config/lib/config.js:175:24)
    at async CustomMain.run (/usr/local/lib/balena-cli/node_modules/@oclif/command/lib/main.js:27:9)
    at async CustomMain._run (/usr/local/lib/balena-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async /usr/local/lib/balena-cli/build/app.js:76:13
    at async Promise.all (index 2)
    at async oclifRun (/usr/local/lib/balena-cli/build/app.js:94:5)
    at async Object.run (/usr/local/lib/balena-cli/build/app.js:107:9)
    at async run (/usr/local/lib/balena-cli/bin/run:20:2)`
